### ISSUE TITLE
Add report generation

### ISSUE THREAD

**Issue by satsfy** [Zander1983/RedMatterApp#7]
### Expected Time: 2-day

Medical specialists need to generate reports from the tasks they accomplish while using Red Matter app. To this end, this issue has the objective to implement what is going to be needed for them to do such a thing. It involves picking up a subset (selected by the user) of graphs created on a given workspace, alongside with certain metrics such as [standard deviation](https://en.wikipedia.org/wiki/Standard_deviation) and [inter Q range](https://en.wikipedia.org/wiki/Interquartile_range) and compiling those into a nice looking `.pdf` or `.csv` file.

For more information on what data has to be on each file, talk to Tomaz.

### Here is an explanation from Tomaz about what is expected:

*One page where all information about an experiment is integrated and presented. It provides an overlook of the experiment (NR of samples measured, most prominent differences between samples without gating, list of channels where gates have been already set, log of when the user has accessed the sample for editing, maybe a representative graph*

*It should allow the user to quickly decide what the experiment is, what has been done, and maybe indentify trends that he has not seen yet*

*It should be the central decision support page*

*A "connective" tissue between the experiments, where you can scroll through them*

*above that we should only have one more page, where all experiments are connected (by date, by cell type measured, by operator etc...)*

*this top page should work as an ontology*

*this would be a premium options for high frequency users*

![image](https://user-images.githubusercontent.com/45462822/111302691-79824780-8632-11eb-8501-80da528af5cc.png)
*this would be the first slide from the user POW*

![image](https://user-images.githubusercontent.com/45462822/111302892-adf60380-8632-11eb-8c63-691cd2bddb95.png)
*this would be the first user page i guess*

![image](https://user-images.githubusercontent.com/45462822/111302948-bb12f280-8632-11eb-9b08-450184dc8699.png)

Figma reference: https://www.figma.com/file/bE6tb8I9maznh5ez6VbOC4/Untitled?node-id=3%3A0

## Tasks

- [x] Allow user to click on a "Generate Report" button
- [ ] Allow user to select what they want the report to look like
- [ ] Allow user to generate a `.pdf` report
- [ ] Allow user to generate a `.csv` report
- [ ] Allow user to download a `.png` image of a graph
